# Generated by Django 5.2.8 on 2025-12-14 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="friendship",
            options={
                "verbose_name": "Friendship",
                "verbose_name_plural": "Friendships",
            },
        ),
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "verbose_name": "User profile",
                "verbose_name_plural": "User profiles",
            },
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_username_change",
            field=models.DateTimeField(
                blank=True,
                help_text="Date when username was last changed",
                null=True,
                verbose_name="Last username change",
            ),
        ),
        migrations.AlterField(
            model_name="friendship",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Created at"
            ),
        ),
        migrations.AlterField(
            model_name="friendship",
            name="from_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="friendship_requests_sent",
                to=settings.AUTH_USER_MODEL,
                verbose_name="From user",
            ),
        ),
        migrations.AlterField(
            model_name="friendship",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="friendship",
            name="to_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="friendship_requests_received",
                to=settings.AUTH_USER_MODEL,
                verbose_name="To user",
            ),
        ),
        migrations.AlterField(
            model_name="friendship",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Updated at"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(
                blank=True, upload_to="avatars/", verbose_name="Avatar"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="bio",
            field=models.TextField(blank=True, verbose_name="Bio"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Created at"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="location",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Location"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Updated at"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="website",
            field=models.URLField(blank=True, verbose_name="Website"),
        ),
    ]
