# Generated by Django 5.2.8 on 2025-11-25 16:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Название"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Описание"),
                ),
                (
                    "short_description",
                    models.TextField(
                        blank=True,
                        max_length=300,
                        verbose_name="Краткое описание",
                    ),
                ),
                (
                    "privacy",
                    models.CharField(
                        choices=[
                            ("public", "Публичный"),
                            ("private", "Приватный"),
                            ("link", "По ссылке"),
                            ("personal", "Персональный"),
                        ],
                        default="public",
                        max_length=20,
                        verbose_name="Приватность",
                    ),
                ),
                (
                    "route_type",
                    models.CharField(
                        choices=[
                            ("driving", "Автомобильный"),
                            ("walking", "Пеший"),
                            ("cycling", "Велосипедный"),
                            ("mixed", "Смешанный"),
                        ],
                        default="walking",
                        max_length=20,
                        verbose_name="Тип маршрута",
                    ),
                ),
                (
                    "mood",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("calm", "Спокойный"),
                            ("active", "Активный"),
                            ("extreme", "Экстремальный"),
                            ("romantic", "Романтический"),
                            ("family", "Семейный"),
                            ("adventure", "Приключенческий"),
                        ],
                        max_length=20,
                        verbose_name="Настроение",
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("historical", "Исторический"),
                            ("nature", "Природный"),
                            ("urban", "Городской"),
                            ("cultural", "Культурный"),
                            ("gastronomic", "Гастрономический"),
                            ("religious", "Религиозный"),
                            ("architectural", "Архитектурный"),
                        ],
                        max_length=20,
                        verbose_name="Тема",
                    ),
                ),
                (
                    "duration_minutes",
                    models.IntegerField(
                        default=0, verbose_name="Продолжительность (минут)"
                    ),
                ),
                (
                    "total_distance",
                    models.FloatField(
                        default=0, verbose_name="Общее расстояние (км)"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Актуален"),
                ),
                (
                    "has_audio_guide",
                    models.BooleanField(
                        default=False, verbose_name="Есть аудиогид"
                    ),
                ),
                (
                    "is_elderly_friendly",
                    models.BooleanField(
                        default=False, verbose_name="Для пожилых"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Создан"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Обновлён"
                    ),
                ),
                (
                    "last_status_update",
                    models.DateTimeField(
                        auto_now=True,
                        verbose_name="Последнее обновление статуса",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "shared_with",
                    models.ManyToManyField(
                        blank=True,
                        related_name="shared_routes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Доступно для",
                    ),
                ),
            ],
            options={
                "verbose_name": "Маршрут",
                "verbose_name_plural": "Маршруты",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RouteComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст комментария")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Создан"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Обновлён"
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="routes.route",
                        verbose_name="Маршрут",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Комментарий маршрута",
                "verbose_name_plural": "Комментарии маршрута",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RoutePhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="route_photos/", verbose_name="Фото"
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Подпись"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Создано"
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="routes.route",
                        verbose_name="Маршрут",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фото маршрута",
                "verbose_name_plural": "Фото маршрута",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="RoutePoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Название"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Описание"),
                ),
                (
                    "address",
                    models.TextField(blank=True, verbose_name="Адрес"),
                ),
                (
                    "latitude",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(-90.0),
                            django.core.validators.MaxValueValidator(90.0),
                        ],
                        verbose_name="Широта",
                    ),
                ),
                (
                    "longitude",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(-180.0),
                            django.core.validators.MaxValueValidator(180.0),
                        ],
                        verbose_name="Долгота",
                    ),
                ),
                (
                    "elevation",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Высота"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("attraction", "Изюминка"),
                            ("nature", "Естественная"),
                            ("forest", "Лес"),
                            ("bus_stop", "Автобусная остановка"),
                            ("viewpoint", "Смотровая площадка"),
                            ("restaurant", "Ресторан"),
                            ("hotel", "Отель"),
                            ("museum", "Музей"),
                            ("park", "Парк"),
                            ("monument", "Памятник"),
                            ("church", "Храм"),
                            ("beach", "Пляж"),
                        ],
                        max_length=20,
                        verbose_name="Категория",
                    ),
                ),
                (
                    "hint_author",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Автор подсказки",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Теги"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок"
                    ),
                ),
                (
                    "has_panorama",
                    models.BooleanField(
                        default=False, verbose_name="Есть панорама"
                    ),
                ),
                (
                    "audio_guide",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="point_audio/",
                        verbose_name="Аудиогид",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Создано"
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="points",
                        to="routes.route",
                        verbose_name="Маршрут",
                    ),
                ),
            ],
            options={
                "verbose_name": "Точка маршрута",
                "verbose_name_plural": "Точки маршрута",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="PointPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="point_photos/", verbose_name="Фото"
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Подпись"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Создано"
                    ),
                ),
                (
                    "point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="routes.routepoint",
                        verbose_name="Точка маршрута",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фото точки",
                "verbose_name_plural": "Фото точки",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="PointComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст комментария")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Создан"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Обновлён"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
                (
                    "point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="routes.routepoint",
                        verbose_name="Точка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Комментарий точки",
                "verbose_name_plural": "Комментарии точки",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SavedPlace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Название"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("home", "Дом"),
                            ("work", "Работа"),
                            ("favorite", "Избранное"),
                            ("restaurant", "Ресторан"),
                            ("park", "Парк"),
                            ("shop", "Магазин"),
                            ("hotel", "Отель"),
                            ("other", "Другое"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="Категория",
                    ),
                ),
                ("address", models.TextField(verbose_name="Адрес")),
                (
                    "latitude",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(-90.0),
                            django.core.validators.MaxValueValidator(90.0),
                        ],
                        verbose_name="Широта",
                    ),
                ),
                (
                    "longitude",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(-180.0),
                            django.core.validators.MaxValueValidator(180.0),
                        ],
                        verbose_name="Долгота",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, verbose_name="Заметки"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Создано"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_places",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сохраненное место",
                "verbose_name_plural": "Сохраненные места",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.TextField(blank=True, verbose_name="О себе")),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, upload_to="avatars/", verbose_name="Аватар"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Местоположение",
                    ),
                ),
                (
                    "website",
                    models.URLField(blank=True, verbose_name="Веб-сайт"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Создан"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Обновлён"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Профиль пользователя",
                "verbose_name_plural": "Профили пользователей",
            },
        ),
        migrations.CreateModel(
            name="Friendship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "В ожидании"),
                            ("accepted", "Принято"),
                            ("rejected", "Отклонено"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friendship_requests_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friendship_requests_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Дружба",
                "verbose_name_plural": "Дружбы",
                "unique_together": {("from_user", "to_user")},
            },
        ),
        migrations.CreateModel(
            name="RouteFavorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Добавлено"
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to="routes.route",
                        verbose_name="Маршрут",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Избранный маршрут",
                "verbose_name_plural": "Избранные маршруты",
                "unique_together": {("route", "user")},
            },
        ),
        migrations.CreateModel(
            name="RouteRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Оценка",
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, verbose_name="Комментарий"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Создано"
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="routes.route",
                        verbose_name="Маршрут",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Оценка маршрута",
                "verbose_name_plural": "Оценки маршрута",
                "unique_together": {("route", "user")},
            },
        ),
        migrations.CreateModel(
            name="UserVisitedPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visited_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Посещено"
                    ),
                ),
                (
                    "point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="routes.routepoint",
                        verbose_name="Точка",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visited_points",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Посещенная точка",
                "verbose_name_plural": "Посещенные точки",
                "unique_together": {("user", "point")},
            },
        ),
    ]
