# Generated by Django 5.2.8 on 2025-11-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routes", "0002_remove_userprofile_user_delete_friendship_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="country",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Страна"
            ),
        ),
    ]
