# Generated by Django 5.2.8 on 2025-12-05 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routes", "0004_route_qr_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="routephoto",
            name="is_main",
            field=models.BooleanField(
                default=False, verbose_name="Главное фото"
            ),
        ),
    ]
