# Generated by Django 5.2.8 on 2025-12-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routes", "0005_routephoto_is_main"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="duration_display",
            field=models.CharField(
                blank=True,
                help_text="Например: 2-3 часа, 1 день, 30 минут",
                max_length=100,
                verbose_name="Время прохождения (отображение)",
            ),
        ),
    ]
