# Generated by Django 5.2.8 on 2025-12-14 13:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routes", "0006_route_duration_display"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pointcomment",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Point comment",
                "verbose_name_plural": "Point comments",
            },
        ),
        migrations.AlterModelOptions(
            name="pointphoto",
            options={
                "ordering": ["order"],
                "verbose_name": "Point photo",
                "verbose_name_plural": "Point photos",
            },
        ),
        migrations.AlterModelOptions(
            name="route",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Route",
                "verbose_name_plural": "Routes",
            },
        ),
        migrations.AlterModelOptions(
            name="routecomment",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Route comment",
                "verbose_name_plural": "Route comments",
            },
        ),
        migrations.AlterModelOptions(
            name="routefavorite",
            options={
                "verbose_name": "Favorite route",
                "verbose_name_plural": "Favorite routes",
            },
        ),
        migrations.AlterModelOptions(
            name="routephoto",
            options={
                "ordering": ["order"],
                "verbose_name": "Route photo",
                "verbose_name_plural": "Route photos",
            },
        ),
        migrations.AlterModelOptions(
            name="routepoint",
            options={
                "ordering": ["order"],
                "verbose_name": "Route point",
                "verbose_name_plural": "Route points",
            },
        ),
        migrations.AlterModelOptions(
            name="routerating",
            options={
                "verbose_name": "Route rating",
                "verbose_name_plural": "Route ratings",
            },
        ),
        migrations.AlterModelOptions(
            name="savedplace",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Saved place",
                "verbose_name_plural": "Saved places",
            },
        ),
        migrations.AlterModelOptions(
            name="uservisitedpoint",
            options={
                "verbose_name": "Visited point",
                "verbose_name_plural": "Visited points",
            },
        ),
        migrations.AlterField(
            model_name="pointcomment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Created"
            ),
        ),
        migrations.AlterField(
            model_name="pointcomment",
            name="point",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="routes.routepoint",
                verbose_name="Point",
            ),
        ),
        migrations.AlterField(
            model_name="pointcomment",
            name="text",
            field=models.TextField(verbose_name="Comment text"),
        ),
        migrations.AlterField(
            model_name="pointcomment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated"),
        ),
        migrations.AlterField(
            model_name="pointcomment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="pointphoto",
            name="caption",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Caption"
            ),
        ),
        migrations.AlterField(
            model_name="pointphoto",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Created"
            ),
        ),
        migrations.AlterField(
            model_name="pointphoto",
            name="image",
            field=models.ImageField(
                upload_to="point_photos/", verbose_name="Photo"
            ),
        ),
        migrations.AlterField(
            model_name="pointphoto",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Order"),
        ),
        migrations.AlterField(
            model_name="pointphoto",
            name="point",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="routes.routepoint",
                verbose_name="Route point",
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="routes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Author",
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="country",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Country"
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Created"
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="route",
            name="duration_display",
            field=models.CharField(
                blank=True,
                help_text="e.g. 2-3 hours, 1 day, 30 minutes",
                max_length=100,
                verbose_name="Display duration",
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="duration_minutes",
            field=models.IntegerField(
                default=0, verbose_name="Duration (minutes)"
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="has_audio_guide",
            field=models.BooleanField(
                default=False, verbose_name="Has audio guide"
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
        migrations.AlterField(
            model_name="route",
            name="is_elderly_friendly",
            field=models.BooleanField(
                default=False, verbose_name="Elderly-friendly"
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="last_status_update",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Last status update"
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="mood",
            field=models.CharField(
                blank=True,
                choices=[
                    ("calm", "Calm"),
                    ("active", "Active"),
                    ("extreme", "Extreme"),
                    ("romantic", "Romantic"),
                    ("family", "Family"),
                    ("adventure", "Adventure"),
                ],
                max_length=20,
                verbose_name="Mood",
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="route",
            name="privacy",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("private", "Private"),
                    ("link", "Link-only"),
                    ("personal", "Personal"),
                ],
                default="public",
                max_length=20,
                verbose_name="Privacy",
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="qr_code",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="qr_codes/",
                verbose_name="QR code",
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="route_type",
            field=models.CharField(
                choices=[
                    ("driving", "Driving"),
                    ("walking", "Walking"),
                    ("cycling", "Cycling"),
                    ("mixed", "Mixed"),
                ],
                default="walking",
                max_length=20,
                verbose_name="Route type",
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="shared_with",
            field=models.ManyToManyField(
                blank=True,
                related_name="shared_routes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Shared with",
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="short_description",
            field=models.TextField(
                blank=True, max_length=300, verbose_name="Short description"
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="theme",
            field=models.CharField(
                blank=True,
                choices=[
                    ("historical", "Historical"),
                    ("nature", "Nature"),
                    ("urban", "Urban"),
                    ("cultural", "Cultural"),
                    ("gastronomic", "Gastronomic"),
                    ("religious", "Religious"),
                    ("architectural", "Architectural"),
                ],
                max_length=20,
                verbose_name="Theme",
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="total_distance",
            field=models.FloatField(
                default=0, verbose_name="Total distance (km)"
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated"),
        ),
        migrations.AlterField(
            model_name="routecomment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Created"
            ),
        ),
        migrations.AlterField(
            model_name="routecomment",
            name="route",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="routes.route",
                verbose_name="Route",
            ),
        ),
        migrations.AlterField(
            model_name="routecomment",
            name="text",
            field=models.TextField(verbose_name="Comment text"),
        ),
        migrations.AlterField(
            model_name="routecomment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated"),
        ),
        migrations.AlterField(
            model_name="routecomment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="routefavorite",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Added"
            ),
        ),
        migrations.AlterField(
            model_name="routefavorite",
            name="route",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorites",
                to="routes.route",
                verbose_name="Route",
            ),
        ),
        migrations.AlterField(
            model_name="routefavorite",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="routephoto",
            name="caption",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Caption"
            ),
        ),
        migrations.AlterField(
            model_name="routephoto",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Created"
            ),
        ),
        migrations.AlterField(
            model_name="routephoto",
            name="image",
            field=models.ImageField(
                upload_to="route_photos/", verbose_name="Photo"
            ),
        ),
        migrations.AlterField(
            model_name="routephoto",
            name="is_main",
            field=models.BooleanField(
                default=False, verbose_name="Main photo"
            ),
        ),
        migrations.AlterField(
            model_name="routephoto",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Order"),
        ),
        migrations.AlterField(
            model_name="routephoto",
            name="route",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="routes.route",
                verbose_name="Route",
            ),
        ),
        migrations.AlterField(
            model_name="routepoint",
            name="address",
            field=models.TextField(blank=True, verbose_name="Address"),
        ),
        migrations.AlterField(
            model_name="routepoint",
            name="audio_guide",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="point_audio/",
                verbose_name="Audio guide",
            ),
        ),
        migrations.AlterField(
            model_name="routepoint",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("attraction", "Attraction"),
                    ("nature", "Natural"),
                    ("forest", "Forest"),
                    ("bus_stop", "Bus stop"),
                    ("viewpoint", "Viewpoint"),
                    ("restaurant", "Restaurant"),
                    ("hotel", "Hotel"),
                    ("museum", "Museum"),
                    ("park", "Park"),
                    ("monument", "Monument"),
                    ("church", "Church"),
                    ("beach", "Beach"),
                ],
                max_length=20,
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="routepoint",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Created"
            ),
        ),
        migrations.AlterField(
            model_name="routepoint",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="routepoint",
            name="elevation",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Elevation"
            ),
        ),
        migrations.AlterField(
            model_name="routepoint",
            name="has_panorama",
            field=models.BooleanField(
                default=False, verbose_name="Has panorama"
            ),
        ),
        migrations.AlterField(
            model_name="routepoint",
            name="hint_author",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Hint author"
            ),
        ),
        migrations.AlterField(
            model_name="routepoint",
            name="latitude",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(-90.0),
                    django.core.validators.MaxValueValidator(90.0),
                ],
                verbose_name="Latitude",
            ),
        ),
        migrations.AlterField(
            model_name="routepoint",
            name="longitude",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(-180.0),
                    django.core.validators.MaxValueValidator(180.0),
                ],
                verbose_name="Longitude",
            ),
        ),
        migrations.AlterField(
            model_name="routepoint",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="routepoint",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Order"),
        ),
        migrations.AlterField(
            model_name="routepoint",
            name="route",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="points",
                to="routes.route",
                verbose_name="Route",
            ),
        ),
        migrations.AlterField(
            model_name="routepoint",
            name="tags",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Tags"
            ),
        ),
        migrations.AlterField(
            model_name="routerating",
            name="comment",
            field=models.TextField(blank=True, verbose_name="Comment"),
        ),
        migrations.AlterField(
            model_name="routerating",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Created"
            ),
        ),
        migrations.AlterField(
            model_name="routerating",
            name="rating",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="Rating",
            ),
        ),
        migrations.AlterField(
            model_name="routerating",
            name="route",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings",
                to="routes.route",
                verbose_name="Route",
            ),
        ),
        migrations.AlterField(
            model_name="routerating",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="savedplace",
            name="address",
            field=models.TextField(verbose_name="Address"),
        ),
        migrations.AlterField(
            model_name="savedplace",
            name="category",
            field=models.CharField(
                choices=[
                    ("home", "Home"),
                    ("work", "Work"),
                    ("favorite", "Favorite"),
                    ("restaurant", "Restaurant"),
                    ("park", "Park"),
                    ("shop", "Shop"),
                    ("hotel", "Hotel"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="savedplace",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Created"
            ),
        ),
        migrations.AlterField(
            model_name="savedplace",
            name="latitude",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(-90.0),
                    django.core.validators.MaxValueValidator(90.0),
                ],
                verbose_name="Latitude",
            ),
        ),
        migrations.AlterField(
            model_name="savedplace",
            name="longitude",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(-180.0),
                    django.core.validators.MaxValueValidator(180.0),
                ],
                verbose_name="Longitude",
            ),
        ),
        migrations.AlterField(
            model_name="savedplace",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="savedplace",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Notes"),
        ),
        migrations.AlterField(
            model_name="savedplace",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saved_places",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="uservisitedpoint",
            name="point",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="routes.routepoint",
                verbose_name="Point",
            ),
        ),
        migrations.AlterField(
            model_name="uservisitedpoint",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="visited_points",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="uservisitedpoint",
            name="visited_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Visited at"
            ),
        ),
    ]
