# Generated by Django 5.2.8 on 2025-12-14 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "routes",
            "0007_alter_pointcomment_options_alter_pointphoto_options_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="route",
            name="mood",
        ),
        migrations.RemoveField(
            model_name="route",
            name="theme",
        ),
        migrations.DeleteModel(
            name="SavedPlace",
        ),
    ]
