# Generated by Django 5.2.8 on 2025-12-12 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "chat",
            "0002_alter_routechat_options_alter_privatemessage_content_and_more",
        ),
        ("routes", "0006_route_duration_display"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="conversation",
            options={
                "ordering": ["-updated_at"],
                "verbose_name": "Conversation",
                "verbose_name_plural": "Conversations",
            },
        ),
        migrations.AlterModelOptions(
            name="privatemessage",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Private message",
                "verbose_name_plural": "Private messages",
            },
        ),
        migrations.AlterModelOptions(
            name="routechat",
            options={
                "ordering": ["-updated_at"],
                "verbose_name": "Route chat",
                "verbose_name_plural": "Route chats",
            },
        ),
        migrations.AlterModelOptions(
            name="routechatmessage",
            options={
                "ordering": ["timestamp"],
                "verbose_name": "Route chat message",
                "verbose_name_plural": "Route chat messages",
            },
        ),
        migrations.AlterField(
            model_name="privatemessage",
            name="content",
            field=models.TextField(max_length=1000, verbose_name="Message"),
        ),
        migrations.AlterField(
            model_name="privatemessage",
            name="conversation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="chat.conversation",
                verbose_name="Conversation",
            ),
        ),
        migrations.AlterField(
            model_name="privatemessage",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Created"
            ),
        ),
        migrations.AlterField(
            model_name="privatemessage",
            name="is_read",
            field=models.BooleanField(default=False, verbose_name="Read"),
        ),
        migrations.AlterField(
            model_name="privatemessage",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_messages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Sender",
            ),
        ),
        migrations.AlterField(
            model_name="routechat",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Created"
            ),
        ),
        migrations.AlterField(
            model_name="routechat",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
        migrations.AlterField(
            model_name="routechat",
            name="route",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat",
                to="routes.route",
                verbose_name="Route",
            ),
        ),
        migrations.AlterField(
            model_name="routechat",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated"),
        ),
        migrations.AlterField(
            model_name="routechatmessage",
            name="is_read",
            field=models.BooleanField(default=False, verbose_name="Read"),
        ),
        migrations.AlterField(
            model_name="routechatmessage",
            name="message",
            field=models.TextField(max_length=1000, verbose_name="Message"),
        ),
        migrations.AlterField(
            model_name="routechatmessage",
            name="route_chat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="chat.routechat",
                verbose_name="Route chat",
            ),
        ),
        migrations.AlterField(
            model_name="routechatmessage",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Time"),
        ),
        migrations.AlterField(
            model_name="routechatmessage",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
