# Generated by Django 5.2.8 on 2025-11-30 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("routes", "0004_route_qr_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AudioGeneration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "В ожидании"),
                            ("processing", "Обрабатывается"),
                            ("completed", "Завершено"),
                            ("failed", "Ошибка"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "voice_type",
                    models.CharField(
                        choices=[
                            ("alloy", "Alloy (нейтральный)"),
                            ("echo", "Echo (мужской)"),
                            ("fable", "Fable (сказочный)"),
                            ("onyx", "Onyx (глубокий)"),
                            ("nova", "Nova (женский)"),
                            ("shimmer", "Shimmer (легкий)"),
                        ],
                        default="alloy",
                        max_length=20,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("auto", "Автоопределение"),
                            ("ru-RU", "Русский"),
                            ("en-US", "Английский"),
                            ("es-ES", "Испанский"),
                            ("fr-FR", "Французский"),
                            ("de-DE", "Немецкий"),
                        ],
                        default="auto",
                        max_length=10,
                    ),
                ),
                (
                    "audio_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="audio_guides/%Y/%m/%d/",
                    ),
                ),
                ("text_content", models.TextField()),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("processing_time", models.FloatField(blank=True, null=True)),
                (
                    "is_route_audio",
                    models.BooleanField(
                        default=False, verbose_name="Аудио всего маршрута"
                    ),
                ),
                (
                    "point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audio_generations",
                        to="routes.routepoint",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audio_generations",
                        to="routes.route",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Генерация аудио",
                "verbose_name_plural": "Генерации аудио",
                "db_table": "ai_audio_generations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RouteAudioGuide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "audio_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="route_audio_guides/%Y/%m/%d/",
                    ),
                ),
                ("total_points", models.IntegerField(default=0)),
                ("total_duration", models.FloatField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processing", "Формируется"),
                            ("completed", "Завершено"),
                            ("failed", "Ошибка"),
                        ],
                        default="processing",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "route",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="full_audio_guide",
                        to="routes.route",
                    ),
                ),
            ],
            options={
                "verbose_name": "Аудиогид маршрута",
                "verbose_name_plural": "Аудиогиды маршрутов",
            },
        ),
        migrations.CreateModel(
            name="VoiceProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preferred_voice",
                    models.CharField(
                        choices=[
                            ("alloy", "Alloy (нейтральный)"),
                            ("echo", "Echo (мужской)"),
                            ("fable", "Fable (сказочный)"),
                            ("onyx", "Onyx (глубокий)"),
                            ("nova", "Nova (женский)"),
                            ("shimmer", "Shimmer (легкий)"),
                        ],
                        default="alloy",
                        max_length=20,
                    ),
                ),
                (
                    "preferred_language",
                    models.CharField(
                        choices=[
                            ("auto", "Автоопределение"),
                            ("ru-RU", "Русский"),
                            ("en-US", "Английский"),
                            ("es-ES", "Испанский"),
                            ("fr-FR", "Французский"),
                            ("de-DE", "Немецкий"),
                        ],
                        default="auto",
                        max_length=10,
                    ),
                ),
                (
                    "auto_generate",
                    models.BooleanField(
                        default=False,
                        help_text="Автоматически генерировать аудио для новых точек",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voice_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Голосовой профиль",
                "verbose_name_plural": "Голосовые профили",
            },
        ),
    ]
