# Generated by Django 5.2.8 on 2025-12-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_audio", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="voiceprofile",
            name="user",
        ),
        migrations.AlterModelOptions(
            name="audiogeneration",
            options={},
        ),
        migrations.RemoveField(
            model_name="audiogeneration",
            name="is_route_audio",
        ),
        migrations.RemoveField(
            model_name="audiogeneration",
            name="route",
        ),
        migrations.AlterField(
            model_name="audiogeneration",
            name="audio_file",
            field=models.FileField(
                blank=True, null=True, upload_to="audio_guides/"
            ),
        ),
        migrations.AlterField(
            model_name="audiogeneration",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="audiogeneration",
            name="language",
            field=models.CharField(
                choices=[
                    ("auto", "Автоопределение"),
                    ("ru-RU", "Русский"),
                    ("en-US", "Английский"),
                    ("es-ES", "Испанский"),
                    ("fr-FR", "Французский"),
                ],
                default="ru-RU",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="audiogeneration",
            name="status",
            field=models.CharField(default="queued", max_length=20),
        ),
        migrations.AlterField(
            model_name="audiogeneration",
            name="voice_type",
            field=models.CharField(
                choices=[
                    ("alloy", "Alloy (нейтральный)"),
                    ("echo", "Echo (мужской)"),
                    ("nova", "Nova (женский)"),
                    ("onyx", "Onyx (глубокий)"),
                    ("fable", "Fable (сказочный)"),
                    ("shimmer", "Shimmer (лёгкий)"),
                ],
                default="alloy",
                max_length=20,
            ),
        ),
        migrations.AlterModelTable(
            name="audiogeneration",
            table=None,
        ),
        migrations.DeleteModel(
            name="RouteAudioGuide",
        ),
        migrations.DeleteModel(
            name="VoiceProfile",
        ),
    ]
