# Generated by Django 5.2.8 on 2025-12-17 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_audio", "0002_remove_voiceprofile_user_and_more"),
        ("routes", "0008_remove_route_mood_remove_route_theme_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="audiogeneration",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Audio generation",
                "verbose_name_plural": "Audio generations",
            },
        ),
        migrations.AddField(
            model_name="audiogeneration",
            name="is_route_audio",
            field=models.BooleanField(
                default=False, verbose_name="Route-level audio"
            ),
        ),
        migrations.AlterField(
            model_name="audiogeneration",
            name="audio_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="audio_guides/",
                verbose_name="Audio file",
            ),
        ),
        migrations.AlterField(
            model_name="audiogeneration",
            name="completed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Completed"
            ),
        ),
        migrations.AlterField(
            model_name="audiogeneration",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Created"
            ),
        ),
        migrations.AlterField(
            model_name="audiogeneration",
            name="error_message",
            field=models.TextField(
                blank=True, null=True, verbose_name="Error message"
            ),
        ),
        migrations.AlterField(
            model_name="audiogeneration",
            name="language",
            field=models.CharField(
                choices=[
                    ("auto", "Auto-detect"),
                    ("ru-RU", "Russian"),
                    ("en-US", "English"),
                    ("es-ES", "Spanish"),
                    ("fr-FR", "French"),
                ],
                default="ru-RU",
                max_length=10,
                verbose_name="Language",
            ),
        ),
        migrations.AlterField(
            model_name="audiogeneration",
            name="point",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audio_generations",
                to="routes.routepoint",
                verbose_name="Point",
            ),
        ),
        migrations.AlterField(
            model_name="audiogeneration",
            name="processing_time",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Processing time (sec)"
            ),
        ),
        migrations.AlterField(
            model_name="audiogeneration",
            name="status",
            field=models.CharField(
                default="queued", max_length=20, verbose_name="Status"
            ),
        ),
        migrations.AlterField(
            model_name="audiogeneration",
            name="text_content",
            field=models.TextField(verbose_name="Text content"),
        ),
        migrations.AlterField(
            model_name="audiogeneration",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="audiogeneration",
            name="voice_type",
            field=models.CharField(
                choices=[
                    ("alloy", "Alloy (neutral)"),
                    ("echo", "Echo (male)"),
                    ("nova", "Nova (female)"),
                    ("onyx", "Onyx (deep)"),
                    ("fable", "Fable (storyteller)"),
                    ("shimmer", "Shimmer (soft)"),
                ],
                default="alloy",
                max_length=20,
                verbose_name="Voice type",
            ),
        ),
    ]
